### ISSUE TITLE
Author missing

### ISSUE THREAD

**Issue by fr34kyn01535** [legastero/jxt-atom#1]
How would i go about fetching the author, as its not a single text field but 

```
<author><name/><uri>xmpp:fr34kyn01535@bam.yt</uri></author>
```

?

**Comment by legastero** [comment]
Support added, and for contributors.

See https://github.com/legastero/jxt-atom/blob/master/index.js#L47-L52 and https://github.com/legastero/jxt-atom/blob/master/index.js#L14-L19
